# Application Properties
spring:
  application:
    name: StudHub
  # Jpa Properties
  datasource:
    #url: jdbc:mysql://localhost:3306/studhub
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none

  # Liquibase properties
  devtools:
    restart:
      enabled: true
  liquibase:
    contexts: dev
    change-log: classpath:db/db.changelog-master.xml

## Server Properties
server:
  port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true

